# Generated by Django 2.1.5 on 2019-02-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'tweet', 'verbose_name_plural': 'tweets'},
        ),
    ]
