# Generated by Django 2.1.5 on 2019-02-16 13:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[core.validators.checkurl]),
        ),
    ]
