# Generated by Django 2.1.5 on 2019-02-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190216_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-updated_at',), 'verbose_name': 'tweet', 'verbose_name_plural': 'tweets'},
        ),
    ]
